import = ["/home/aaron/.config/alacritty/tokyo-night-storm.toml"]

[font]
size = 17

[font.bold]
family = "InconsolataNerdFont"
style = "Bold"

[font.bold_italic]
family = "InconsolataNerdFont"
style = "Bold Italic"

[font.italic]
family = "InconsolataNerdFont"
style = "Italic"

[font.normal]
family = "InconsolataNerdFont"
style = "Regular"

[shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/usr/bin/bash"

[window]
# startup_mode = "Windowed"
startup_mode = "Fullscreen"
