[env]
TERM = "xterm-256color"

[font]
size = 16

normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
# "InconsolataNerdFont"

[terminal.shell]
args = ["-l", "-c", "zellij attach --index 0 || zellij"]
program = "/usr/bin/bash"

[window]
# startup_mode = "Windowed"
startup_mode = "Fullscreen"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[general]
# import = ["/home/aaron/.config/alacritty/gruvbox_material_medium_light.toml"]
import = ["/home/aaron/.config/alacritty/catppuccin-latte.toml"]
